// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
//
// Code generated by Microsoft (R) Rust Code Generator. DO NOT EDIT.

mod generated;
pub use generated::*;
pub mod alternate_initial_verb;
pub mod continuation_token;
