// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Rust Code Generator.

#![cfg_attr(docsrs, feature(doc_cfg))]

mod generated;
pub use generated::*;

// Touch the fields so `dead_code` stays enabled elsewhere without modifying generated files.
#[allow(dead_code)]
const _: () = {
    fn _touch_misc_tests_client_list_widgets_options() {
        let client = MiscTestsClient::with_no_credential("https://contoso.com", None).unwrap();
        let _ = client.list_widgets(None);
    }
};
