// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Rust Code Generator. DO NOT EDIT.

// this should be preserved and is not next to the begin delimiter.

// this should also be preserved right next to the begin delimiter.
// BEGIN GENERATED CODE -- do not edit from here till END
mod generated;

pub mod clients {
    pub use crate::generated::clients::{
        AppendBlobClient, AppendBlobClientOptions, BlobClient, BlobClientOptions,
        BlobContainerClient, BlobContainerClientOptions, BlobServiceClient,
        BlobServiceClientOptions, BlockBlobClient, BlockBlobClientOptions, PageBlobClient,
        PageBlobClientOptions,
    };
}

pub mod models {
    pub use crate::generated::clients::method_options::{
        AppendBlobClientAppendBlockFromUrlOptions, AppendBlobClientAppendBlockOptions,
        AppendBlobClientCreateOptions, AppendBlobClientSealOptions,
        BlobClientAbortCopyFromUrlOptions, BlobClientAcquireLeaseOptions,
        BlobClientBreakLeaseOptions, BlobClientChangeLeaseOptions, BlobClientCopyFromUrlOptions,
        BlobClientCreateSnapshotOptions, BlobClientDeleteImmutabilityPolicyOptions,
        BlobClientDeleteOptions, BlobClientDownloadOptions, BlobClientGetAccountInfoOptions,
        BlobClientGetPropertiesOptions, BlobClientGetTagsOptions, BlobClientReleaseLeaseOptions,
        BlobClientRenewLeaseOptions, BlobClientSetExpiryOptions, BlobClientSetHttpHeadersOptions,
        BlobClientSetImmutabilityPolicyOptions, BlobClientSetLegalHoldOptions,
        BlobClientSetMetadataOptions, BlobClientSetTagsOptions, BlobClientSetTierOptions,
        BlobClientStartCopyFromUrlOptions, BlobClientUndeleteOptions,
        BlobContainerClientAcquireLeaseOptions, BlobContainerClientBreakLeaseOptions,
        BlobContainerClientChangeLeaseOptions, BlobContainerClientCreateOptions,
        BlobContainerClientDeleteOptions, BlobContainerClientFilterBlobsOptions,
        BlobContainerClientGetAccessPolicyOptions, BlobContainerClientGetAccountInfoOptions,
        BlobContainerClientGetPropertiesOptions, BlobContainerClientListBlobFlatSegmentOptions,
        BlobContainerClientListBlobHierarchySegmentOptions, BlobContainerClientReleaseLeaseOptions,
        BlobContainerClientRenameOptions, BlobContainerClientRenewLeaseOptions,
        BlobContainerClientRestoreOptions, BlobContainerClientSetAccessPolicyOptions,
        BlobContainerClientSetMetadataOptions, BlobContainerClientSubmitBatchOptions,
        BlobServiceClientFilterBlobsOptions, BlobServiceClientGetAccountInfoOptions,
        BlobServiceClientGetPropertiesOptions, BlobServiceClientGetStatisticsOptions,
        BlobServiceClientGetUserDelegationKeyOptions,
        BlobServiceClientListContainersSegmentOptions, BlobServiceClientSetPropertiesOptions,
        BlobServiceClientSubmitBatchOptions, BlockBlobClientCommitBlockListOptions,
        BlockBlobClientGetBlockListOptions, BlockBlobClientPutBlobFromUrlOptions,
        BlockBlobClientQueryOptions, BlockBlobClientStageBlockFromUrlOptions,
        BlockBlobClientStageBlockOptions, BlockBlobClientUploadOptions,
        PageBlobClientClearPagesOptions, PageBlobClientCopyIncrementalOptions,
        PageBlobClientCreateOptions, PageBlobClientGetPageRangesDiffOptions,
        PageBlobClientGetPageRangesOptions, PageBlobClientResizeOptions,
        PageBlobClientUpdateSequenceNumberOptions, PageBlobClientUploadPagesFromUrlOptions,
        PageBlobClientUploadPagesOptions,
    };
    pub use crate::generated::enums::*;
    pub use crate::generated::header_traits::*;
    pub use crate::generated::models::*;
}

pub use crate::generated::clients::{
    AppendBlobClient, AppendBlobClientOptions, BlobClient, BlobClientOptions, BlobContainerClient,
    BlobContainerClientOptions, BlobServiceClient, BlobServiceClientOptions, BlockBlobClient,
    BlockBlobClientOptions, PageBlobClient, PageBlobClientOptions,
};
// END GENERATED CODE
// this should also be preserved right next to the end delimiter.

// this should also be preserved and is not next to the end delimiter.
