// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Rust Code Generator. DO NOT EDIT.

// this should be preserved and is not next to the begin delimiter.

// this should also be preserved right next to the begin delimiter.
// BEGIN GENERATED CODE -- do not edit from here till END
mod generated;

pub mod clients {
    pub use crate::generated::clients::{
        BlobAppendBlobClient, BlobBlobClient, BlobBlockBlobClient, BlobClient, BlobClientOptions,
        BlobContainerClient, BlobPageBlobClient, BlobServiceClient,
    };
}

pub mod models {
    pub use crate::generated::clients::method_options::{
        BlobAppendBlobClientAppendBlockFromUrlOptions, BlobAppendBlobClientAppendBlockOptions,
        BlobAppendBlobClientCreateOptions, BlobAppendBlobClientSealOptions,
        BlobBlobClientAbortCopyFromUrlOptions, BlobBlobClientAcquireLeaseOptions,
        BlobBlobClientBreakLeaseOptions, BlobBlobClientChangeLeaseOptions,
        BlobBlobClientCopyFromUrlOptions, BlobBlobClientCreateSnapshotOptions,
        BlobBlobClientDeleteImmutabilityPolicyOptions, BlobBlobClientDeleteOptions,
        BlobBlobClientDownloadOptions, BlobBlobClientGetAccountInfoOptions,
        BlobBlobClientGetPropertiesOptions, BlobBlobClientGetTagsOptions,
        BlobBlobClientReleaseLeaseOptions, BlobBlobClientRenewLeaseOptions,
        BlobBlobClientSetExpiryOptions, BlobBlobClientSetHttpHeadersOptions,
        BlobBlobClientSetImmutabilityPolicyOptions, BlobBlobClientSetLegalHoldOptions,
        BlobBlobClientSetMetadataOptions, BlobBlobClientSetTagsOptions,
        BlobBlobClientSetTierOptions, BlobBlobClientStartCopyFromUrlOptions,
        BlobBlobClientUndeleteOptions, BlobBlockBlobClientCommitBlockListOptions,
        BlobBlockBlobClientGetBlockListOptions, BlobBlockBlobClientPutBlobFromUrlOptions,
        BlobBlockBlobClientQueryOptions, BlobBlockBlobClientStageBlockFromUrlOptions,
        BlobBlockBlobClientStageBlockOptions, BlobBlockBlobClientUploadOptions,
        BlobContainerClientAcquireLeaseOptions, BlobContainerClientBreakLeaseOptions,
        BlobContainerClientChangeLeaseOptions, BlobContainerClientCreateOptions,
        BlobContainerClientDeleteOptions, BlobContainerClientFilterBlobsOptions,
        BlobContainerClientGetAccessPolicyOptions, BlobContainerClientGetAccountInfoOptions,
        BlobContainerClientGetPropertiesOptions, BlobContainerClientListBlobFlatSegmentOptions,
        BlobContainerClientListBlobHierarchySegmentOptions, BlobContainerClientReleaseLeaseOptions,
        BlobContainerClientRenameOptions, BlobContainerClientRenewLeaseOptions,
        BlobContainerClientRestoreOptions, BlobContainerClientSetAccessPolicyOptions,
        BlobContainerClientSetMetadataOptions, BlobContainerClientSubmitBatchOptions,
        BlobPageBlobClientClearPagesOptions, BlobPageBlobClientCopyIncrementalOptions,
        BlobPageBlobClientCreateOptions, BlobPageBlobClientGetPageRangesDiffOptions,
        BlobPageBlobClientGetPageRangesOptions, BlobPageBlobClientResizeOptions,
        BlobPageBlobClientUpdateSequenceNumberOptions, BlobPageBlobClientUploadPagesFromUrlOptions,
        BlobPageBlobClientUploadPagesOptions, BlobServiceClientFilterBlobsOptions,
        BlobServiceClientGetAccountInfoOptions, BlobServiceClientGetPropertiesOptions,
        BlobServiceClientGetStatisticsOptions, BlobServiceClientGetUserDelegationKeyOptions,
        BlobServiceClientListContainersSegmentOptions, BlobServiceClientSetPropertiesOptions,
        BlobServiceClientSubmitBatchOptions,
    };
    pub use crate::generated::enums::*;
    pub use crate::generated::header_traits::*;
    pub use crate::generated::models::*;
}

pub use crate::generated::clients::{BlobClient, BlobClientOptions};
// END GENERATED CODE
// this should also be preserved right next to the end delimiter.

// this should also be preserved and is not next to the end delimiter.
