trigger: none
pr: none

pool:
  vmImage: "ubuntu-22.04"

steps:
  - template: ../steps/set-env.yaml

  - template: ../steps/build-test.yaml

  - pwsh: |
      $currentVersion = node -p -e "require('$(System.DefaultWorkingDirectory)/packages/typespec-rust/package.json').version";
      $currentVersion="$currentVersion-$(Build.BuildNumber)";
      cd packages/typespec-rust
      npm version --no-git-tag-version $currentVersion
      npm pack;
      npm install -g azure-tools-typespec-rust-$currentVersion.tgz
      if ($LASTEXITCODE) {
        exit $LASTEXITCODE
      }
      npx publish-release --token $(azuresdk-github-pat) --repo autorest.rust --owner azure --name "TypeSpec emitter for Rust v$currentVersion" --tag v$currentVersion --notes='Beta version of TypeSpec emitter for Rust SDKs' --prerelease --editRelease false --assets azure-tools-typespec-rust-$currentVersion.tgz --target_commitish $(Build.SourceBranchName);
    displayName: "Publish Dev Release"
