// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Rust Code Generator.

#![cfg_attr(docsrs, feature(doc_cfg))]

mod generated;
pub mod models;
pub mod clients {
    pub use super::generated::clients::*;
}
pub use generated::{AlternateTypesClient, AlternateTypesClientOptions};
