// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Rust Code Generator. DO NOT EDIT.

// BEGIN GENERATED CODE -- do not edit from here till END
mod generated;

pub mod clients {
    pub use crate::generated::clients::{
        ClientModelClient, NamingClient, NamingClientOptions, NamingUnionEnumClient,
    };
}

pub mod models {
    pub use crate::generated::clients::method_options::{
        ClientModelClientClientOptions, ClientModelClientLanguageOptions,
        NamingClientClientNameOptions, NamingClientClientOptions,
        NamingClientCompatibleWithEncodedNameOptions, NamingClientLanguageOptions,
        NamingClientParameterOptions, NamingClientRequestOptions, NamingClientResponseOptions,
        NamingUnionEnumClientUnionEnumMemberNameOptions, NamingUnionEnumClientUnionEnumNameOptions,
    };
    pub use crate::generated::enums::*;
    pub use crate::generated::header_traits::*;
    pub use crate::generated::models::*;
}

pub use crate::generated::clients::{NamingClient, NamingClientOptions};
// END GENERATED CODE
